name: robotwin2_easy5_demo20

task_entries: &task_entries
  - task_name: beat_block_hammer
    setting: demo_clean
    zarr_path: /DATA/disk0/zykh/wzy/code/R3D-Policy/R3D/data/robotwin2_demo20/beat_block_hammer-demo_clean-20-seed0.zarr
    text_command: beat_block_hammer
  - task_name: move_playingcard_away
    setting: demo_clean
    zarr_path: /DATA/disk0/zykh/wzy/code/R3D-Policy/R3D/data/robotwin2_demo20/move_playingcard_away-demo_clean-20-seed0.zarr
    text_command: move_playingcard_away
  - task_name: turn_switch
    setting: demo_clean
    zarr_path: /DATA/disk0/zykh/wzy/code/R3D-Policy/R3D/data/robotwin2_demo20/turn_switch-demo_clean-20-seed0.zarr
    text_command: turn_switch
  - task_name: open_microwave
    setting: demo_clean
    zarr_path: /DATA/disk0/zykh/wzy/code/R3D-Policy/R3D/data/robotwin2_demo20/open_microwave-demo_clean-20-seed0.zarr
    text_command: open_microwave
  - task_name: place_shoe
    setting: demo_clean
    zarr_path: /DATA/disk0/zykh/wzy/code/R3D-Policy/R3D/data/robotwin2_demo20/place_shoe-demo_clean-20-seed0.zarr
    text_command: place_shoe

shape_meta: &shape_meta
  obs:
    point_cloud:
      shape: [1024, 6]
      type: point_cloud
    agent_pos:
      shape: [14]
      type: low_dim
    task_onehot:
      shape: [5]
      type: low_dim
  action:
    shape: [14]

env_runner:
  _target_: r3d.env_runner.robotwin2_runner.RoboTwin2Runner
  output_dir: ${hydra:run.dir}
  task_name: null
  task_entries: *task_entries
  eval_task_name: ${eval_task_name}
  seed: 0
  eval_episodes: 20
  max_steps: 2000
  n_obs_steps: ${n_obs_steps}
  n_action_steps: ${n_action_steps}
  task_config: demo_clean
  instruction_type: unseen
  action_space_type: joint
  head_camera_type: D435
  save_video: false
  tqdm_interval_sec: 5.0

dataset:
  _target_: r3d.dataset.multi_robotwin_dataset.MultiRobotwinDataset
  tasks: *task_entries
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  seed: 42
  val_ratio: 0.0
  max_train_episodes: null
  balanced_sampling: true
  use_data_augmentation: ${data_augmentation.use_augmentation}
  pc_xyz_noise_std: ${data_augmentation.pc_xyz_noise_std}
  pc_rgb_noise_std: ${data_augmentation.pc_rgb_noise_std}
  agent_pos_noise_std: ${data_augmentation.agent_pos_noise_std}
  use_color_jitter: ${data_augmentation.use_color_jitter}
  brightness_range: ${data_augmentation.brightness_range}
  contrast_range: ${data_augmentation.contrast_range}
  saturation_range: ${data_augmentation.saturation_range}
  use_target_ee: ${policy.use_target_ee}
  text_json_path: /DATA/disk0/zykh/wzy/code/R3D-Policy/R3D/data/text.json
  return_text: ${policy.use_text}
  strict_text_lookup: false
