name: r3d-release
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pytorch=2.4.1
  - torchvision=0.19.1
  - pytorch-cuda=12.1
  - pip
  - setuptools>=68
  - wheel
  - ninja
  - cmake
  - gcc_linux-64=11
  - gxx_linux-64=11
  - pip:
      - -r environment/requirements.txt
